Add scaffle
lissrbay/bug_ml pull request #3
Opened 2022-01-14 09:40 UTC by lissrbay

1) У нас тэггер все еще с фрейм энкодером или репорт энкодим?
2а) Хочется как то получать число фреймов  в репорте для модельки 
2) В общем, скаффлу тут пока нехорошо

2022-01-14 11:57 UTC, akhvorov commented
Там кажется попали __pycache__ файлы и еще что-то лишнее, может удалим?)

2022-01-18 10:23 UTC, akhvorov requested changes

2022-01-18 10:23 UTC, akhvorov commented on new/model/frame_encoders/scaffle.py
> +def clean_method_name(method_name):
Может это сделать общим для всех методов? Возможно для скафла тоже какая-то предобработка нужна, но наверное уже более специфичная

2022-01-18 10:23 UTC, akhvorov commented on new/model/frame_encoders/scaffle.py
>      def encode(self, frame: Frame) -> torch.Tensor:
Так это же не кодировщий фрейма, это кодировщик слов. На фрейм должен получаться один вектор, поэтому и RNN должна тут применяться

2022-01-21 10:58 UTC, akhvorov requested changes

2022-01-21 10:58 UTC, akhvorov commented on new/data/embs_dataset.py
> +        emb_pos = self.report_idx_to_emb_pos[id]
Кажется этот код никогда не запускался, тут название переменной несуществующей

2022-01-21 10:58 UTC, akhvorov commented on new/data/report.py
> +            return Report(0, [], '', [])
Мы так ошибку пропустим( Давай частно падать в таких случаях или хотя бы None возвращать

2022-01-21 10:58 UTC, akhvorov commented on new/data/report.py
> +            new_frame = Frame('', method_meta)
А чего все поля переехали в meta? Наверное это не очень страшно, но как будто им норм быть и просто полями

2022-01-21 10:58 UTC, akhvorov commented on new/data/report.py
> +                           'exception_class': self.exceptions}
А почему класс эксепшена передается в фрейм? Он же на весь репорт один. Если это для подсчета фичей, то у нас же теперь не FrameEncoder, а ReportEncoder, так что проблем быть не должно иметь эту инфу только на уровне репорта, не дублируя

2022-01-21 10:58 UTC, akhvorov commented on new/data/report.py
> +        report = Report(_id, exceptions, '', frames)
А что за третий аргумент и зачем он тогда нужен, если он всегда пустая строка?

2022-01-21 10:58 UTC, akhvorov commented on new/data_aggregation/add_path_info.py
> +    parser.add_argument("--intellij_path", type=str)
Может название поменять на более общее, типа repository_path?

2022-01-21 10:58 UTC, akhvorov commented on new/data_aggregation/collect_reports_info.py
> +    collect_commits = ["sudo", "sh", "./collect_fix_commits.sh", args['intellij_path']]
Почему-то в этом файле обращение к полям идет не через точку, а через скобочки)

2022-01-21 10:58 UTC, akhvorov commented on new/data_aggregation/collect_sources.py
> +        os.mkdir(path)
os.makedirs(path, exist_ok=True) заменит весь этот метод

2022-01-21 10:58 UTC, akhvorov commented on new/data_aggregation/get_all_changed_methods.py
> +cmf = ChangedMethodsFinder()
Глобальная переменная(

2022-01-21 10:58 UTC, akhvorov commented on new/data_aggregation/git_data.py
> +            print("Check path to repository. Maybe, you should write path in double quotes\"\"")
Тут тоже предлагаю падать, все равно неясно, что он возвращает в случае неуспеха

2022-01-21 10:58 UTC, akhvorov commented on new/model/report_encoders/code2seq_report_encoder.py
> +    _emb_dim = 320
И тут константы. Надо отдельный файлик для констант сделать

2022-01-21 11:24 UTC, lissrbay commented on new/data_aggregation/get_java_methods.py
> +    commits = ['ecdd37cc44f9beb6870c78c3432b1fddcdab8292~1','ecdd37cc44f9beb6870c78c3432b1fddcdab8292']
это был пример:)

2022-01-21 11:27 UTC, lissrbay commented on new/data/embs_dataset.py
> +        emb_pos = self.report_idx_to_emb_pos[id]
упс, это неудачный ренейминг

2022-01-21 11:38 UTC, lissrbay commented on new/data_aggregation/collect_reports_info.py
> +    collect_commits = ["sudo", "sh", "./collect_fix_commits.sh", args['intellij_path']]
наследие того что это была джейсонина ._. поправлю

2022-01-23 15:50 UTC, merged