Fine tuning
lissrbay/bug_ml pull request #9
Opened 2022-03-17 07:18 UTC by kisate

2022-03-20 14:08 UTC, lissrbay commented on new/data/labeled_path_context_storage.py
> +        self.work_dir = Path("/home/dumtrii/Documents/practos/spring2/bug_ml/tmp/storage")
локальный путь

2022-03-20 15:03 UTC, lissrbay commented on new/model/report_encoders/utils.py
> +def split_into_subtokens(name: str) -> List[str]:
надо еще фильтрануть от мусора наверное
например split_into_subtokens("HelloWorld") дает ['_', 'hello', 'world']

2022-03-26 09:43 UTC, akhvorov requested changes

2022-03-26 09:43 UTC, akhvorov commented on new/data/labeled_path_context_storage.py
> +CACHE_SIZE = 3500
Константы давайте выносить в отдельный файлик, у нас же есть такой даже

2022-03-26 09:43 UTC, akhvorov commented on new/data/labeled_path_context_storage.py
> +        self.path_file_path = self.output_path / "java" / "data" / "path_contexts.c2s"
++

2022-03-26 09:43 UTC, akhvorov commented on new/model/report_encoders/code2seq_report_encoder.py
> +    def __init__(self, model: Code2Seq, context_storage: LabeledPathContextStorage, frames_limit=80, batch_size=32, padding_idx=2):
Типы аргументов

2022-03-26 09:43 UTC, akhvorov commented on new/training/config.json
> +  "code2seq_config_path": "/home/dumtrii/Documents/practos/spring2/code2seq/config/code2seq-java-small.yaml",
А сами эти файлы лежат в репе? Я так понимаю, нет. Как можно тогда у себя это воспроизвести?

2022-03-31 00:05 UTC, merged